name: MCP One-Click Install

on:
  workflow_dispatch:   # Trigger manually from GitHub Actions UI

jobs:
  install-mcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build MCP server
        run: pnpm --filter mcp-server build
